spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bentoya?useTimezone=true&serverTimezone=UTC"
    username: "root"
    password: "localhost"
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true # Configuration to print the JPA query
    hibernate:
      physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Configuration for conversion camelCase to snake_case.
    properties:
      javax:
        persistence:
          jdbc:
            driver: com.mysql.cj.jdbc.Driver
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata