package com.example.bentoyaspring.utils

enum class MenuItems {
    YAKISOBA_P,
    YAKISOBA_G,
    GUIOZA_BOVINO,
    GUIOZA_SUINO,
    GUIOZA_FRANGO,
    GUIOZA_SOJA,
    GUIOZA_SALMAO,
    GUIOZA_ROMEU_JULIETA,
    GUIOZA_DOCE_DE_LEITE,
    HOT_ROLL,
    BENTO_ARROZ_WAKAME,
    BENTO_ARROZ_CURRY,
    BENTO_MACARRAO,
    HOT_ROLL_CARNE
}